# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-28 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_csv_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='type',
        ),
    ]
