# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_csv_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='process_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
