# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-28 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_csv_process_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='archived',
            new_name='is_archived',
        ),
        migrations.RenameField(
            model_name='csv',
            old_name='archived_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='csv',
            name='process_status',
        ),
        migrations.RemoveField(
            model_name='csv',
            name='type',
        ),
        migrations.AddField(
            model_name='csv',
            name='error_status',
            field=models.IntegerField(default=0),
        ),
    ]
