# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-01 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20170228_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='file',
            field=models.FileField(null=True, upload_to=engine.models.upload_path_handler),
        ),
    ]
